// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace CF.POCOGenerator
{

    // Reward
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Reward
    {
        public int Id { get; set; } // Id (Primary key)
        public int ProjectId { get; set; } // ProjectId
        public string Name { get; set; } // Name (length: 50)
        public System.DateTime DateInserted { get; set; } // DateInserted
        public string Description { get; set; } // Description (length: 50)
        public int MinRequiredAmount { get; set; } // MinRequiredAmount
        public int MaxAvailable { get; set; } // MaxAvailable
        public int CurrentAvailable { get; set; } // CurrentAvailable
        public bool IsAvailable { get; set; } // IsAvailable
        public int MaxRequiredAmount { get; set; } // MaxRequiredAmount

        // Foreign keys
        public virtual Project Project { get; set; } // FK_Reward_Project
    }

}
// </auto-generated>
