// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace CF.POCOGenerator
{

    // database_firewall_rules
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class sys_DatabaseFirewallRuleMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<sys_DatabaseFirewallRule>
    {
        public sys_DatabaseFirewallRuleMapping()
            : this("sys")
        {
        }

        public sys_DatabaseFirewallRuleMapping(string schema)
        {
            ToTable("database_firewall_rules", schema);
            HasKey(x => new { x.Id, x.Name, x.StartIpAddress, x.EndIpAddress, x.CreateDate, x.ModifyDate });

            Property(x => x.Id).HasColumnName(@"id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"name").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.StartIpAddress).HasColumnName(@"start_ip_address").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(45);
            Property(x => x.EndIpAddress).HasColumnName(@"end_ip_address").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(45);
            Property(x => x.CreateDate).HasColumnName(@"create_date").IsRequired().HasColumnType("datetime");
            Property(x => x.ModifyDate).HasColumnName(@"modify_date").IsRequired().HasColumnType("datetime");
        }
    }

}
// </auto-generated>
