// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace CF.POCOGenerator
{

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class UserMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<User>
    {
        public UserMapping()
            : this("dbo")
        {
        }

        public UserMapping(string schema)
        {
            ToTable("User", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AspNetUsersId).HasColumnName(@"AspNetUsersId").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.PhotoUrl).HasColumnName(@"PhotoUrl").IsOptional().HasColumnType("nvarchar(max)");
            Property(x => x.Image).HasColumnName(@"Image").IsOptional().HasColumnType("varbinary");

            // Foreign keys
            HasOptional(a => a.AspNetUser).WithMany(b => b.Users).HasForeignKey(c => c.AspNetUsersId).WillCascadeOnDelete(false); // FK_User_AspNetUsers
        }
    }

}
// </auto-generated>
