// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace CF.POCOGenerator
{

    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class FakeCrowdFundingDbContext : ICrowdFundingDbContext
    {
        public System.Data.Entity.DbSet<BackerProject> BackerProjects { get; set; }
        public System.Data.Entity.DbSet<Category> Categories { get; set; }
        public System.Data.Entity.DbSet<Project> Projects { get; set; }
        public System.Data.Entity.DbSet<ProjectStatu> ProjectStatus { get; set; }
        public System.Data.Entity.DbSet<ProjectUpdate> ProjectUpdates { get; set; }
        public System.Data.Entity.DbSet<Reward> Rewards { get; set; }
        public System.Data.Entity.DbSet<Sysdiagram> Sysdiagrams { get; set; }
        public System.Data.Entity.DbSet<User> Users { get; set; }
        public System.Data.Entity.DbSet<UserProjectComment> UserProjectComments { get; set; }

        public FakeCrowdFundingDbContext()
        {
            BackerProjects = new FakeDbSet<BackerProject>("Id");
            Categories = new FakeDbSet<Category>("Id");
            Projects = new FakeDbSet<Project>("Id");
            ProjectStatus = new FakeDbSet<ProjectStatu>("Id");
            ProjectUpdates = new FakeDbSet<ProjectUpdate>("Id");
            Rewards = new FakeDbSet<Reward>("Id");
            Sysdiagrams = new FakeDbSet<Sysdiagram>("DiagramId");
            Users = new FakeDbSet<User>("Id");
            UserProjectComments = new FakeDbSet<UserProjectComment>("Id");
        }

        public int SaveChangesCount { get; private set; }
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync()
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }
    }
}
// </auto-generated>
